/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jahazielmorenolab8;

import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Jahaziel
 */
public class PrincipalLab8 extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalLab8
     */
    public PrincipalLab8() {
        initComponents();
    }
    
    
    // Para boton Abrir
    public void cargarHadas(){
            AdminHadas ap = new AdminHadas("./Hadas.cbm");
            ap.cargarArchivoBinario();
            hadas = ap.getListaHadas();
    }
    
    public void CargarTodo(){
        cargarHadas();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombreLamia = new javax.swing.JTextField();
        tf_alturaLamias = new javax.swing.JTextField();
        tf_edadLamia = new javax.swing.JTextField();
        tf_AletasLamia = new javax.swing.JTextField();
        tf_NBranquiasLamias = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombreHamadrades = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_edadHamadrades = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_alturaHamadrade = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tf_nombreSilfides = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_edadSilfides = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_alturaSilfides = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tf_NAlasSilfides = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombreSalamandra = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_edadSalamandras = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_alturaSalamandras = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tf_NAlasSalamandras = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_nombreLamia1 = new javax.swing.JTextField();
        tf_alturaLamias1 = new javax.swing.JTextField();
        tf_edadLamia1 = new javax.swing.JTextField();
        tf_AletasLamia1 = new javax.swing.JTextField();
        tf_NBranquiasLamias1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        cb_lamias = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tf_nombreHamadrades1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tf_edadHamadrades1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_alturaHamadrade1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        cb_Hamadrades = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        tf_nombreSilfides1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tf_edadSilfides1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_alturaSilfides1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        tf_NAlasSilfides1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        cb_silfides = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        tf_nombreSalamandra1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_edadSalamandras1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_alturaSalamandras1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        tf_NAlasSalamandras1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cb_Salamandras = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cb_player1 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        cb_player2 = new javax.swing.JComboBox<>();
        pg1 = new javax.swing.JProgressBar();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        pg2 = new javax.swing.JProgressBar();
        jLabel40 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        jLabel3.setText("Altura");

        jLabel4.setText("Aletas en cm");

        jLabel5.setText("Numero de Branquias");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(5, 5, 5)))
                    .addComponent(jLabel5))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(tf_NBranquiasLamias, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreLamia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_alturaLamias, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_edadLamia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_AletasLamia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreLamia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_edadLamia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_alturaLamias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_AletasLamia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_NBranquiasLamias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Lamias", jPanel3);

        jLabel6.setText("Nombre");

        jLabel7.setText("Edad");

        jLabel8.setText("Altura");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(105, 105, 105)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(tf_nombreHamadrades, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_alturaHamadrade, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_edadHamadrades, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreHamadrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_edadHamadrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_alturaHamadrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Amadriades", jPanel5);

        jLabel9.setText("Nombre");

        jLabel10.setText("Edad");

        jLabel11.setText("Altura");

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Numero de Alas");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(82, 82, 82)
                        .addComponent(tf_NAlasSilfides))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(tf_nombreSilfides, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_alturaSilfides, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_edadSilfides, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreSilfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_edadSilfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_alturaSilfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_NAlasSilfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Silfides", jPanel6);

        jLabel12.setText("Nombre");

        jLabel13.setText("Edad");

        jLabel14.setText("Altura");

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("Numero de Alas");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(82, 82, 82)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4)
                    .addComponent(tf_nombreSalamandra, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(tf_alturaSalamandras, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(tf_edadSalamandras, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(tf_NAlasSalamandras))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreSalamandra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_edadSalamandras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_alturaSalamandras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_NAlasSalamandras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton4)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Salamandras", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar Hadas", jPanel1);

        jLabel17.setText("Nombre");

        jLabel18.setText("Edad");

        jLabel19.setText("Altura");

        jLabel20.setText("Aletas en cm");

        jLabel21.setText("Numero de Branquias");

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel33.setText("Lamias");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel33))
                            .addGap(5, 5, 5)))
                    .addComponent(jLabel21))
                .addGap(59, 59, 59)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(tf_NBranquiasLamias1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreLamia1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_alturaLamias1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_edadLamia1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_AletasLamia1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_lamias, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cb_lamias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreLamia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_edadLamia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_alturaLamias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_AletasLamia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_NBranquiasLamias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton5)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Lamias", jPanel8);

        jLabel22.setText("Nombre");

        jLabel23.setText("Edad");

        jLabel24.setText("Altura");

        jButton6.setText("Agregar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel34.setText("Hamadrades");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(105, 105, 105))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_Hamadrades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton6)
                        .addComponent(tf_nombreHamadrades1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_alturaHamadrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_edadHamadrades1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cb_Hamadrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreHamadrades1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_edadHamadrades1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_alturaHamadrade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton6)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Amadriades", jPanel9);

        jLabel25.setText("Nombre");

        jLabel26.setText("Edad");

        jLabel27.setText("Altura");

        jButton7.setText("Agregar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel28.setText("Numero de Alas");

        jLabel36.setText("Silfides");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(82, 82, 82)
                                .addComponent(tf_NAlasSilfides1))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7)
                                    .addComponent(tf_nombreSilfides1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_alturaSilfides1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_edadSilfides1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cb_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreSilfides1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_edadSilfides1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_alturaSilfides1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_NAlasSilfides1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Silfides", jPanel10);

        jLabel29.setText("Nombre");

        jLabel30.setText("Edad");

        jLabel31.setText("Altura");

        jButton8.setText("Agregar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel32.setText("Numero de Alas");

        jLabel35.setText("Hamadrades");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(cb_Salamandras, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton8)
                            .addComponent(tf_nombreSalamandra1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tf_alturaSalamandras1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tf_edadSalamandras1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tf_NAlasSalamandras1))))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cb_Salamandras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreSalamandra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_edadSalamandras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tf_alturaSalamandras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_NAlasSalamandras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton8)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Salamandras", jPanel11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar/elminar", jPanel2);

        jLabel37.setText("VS");

        pg1.setForeground(new java.awt.Color(102, 102, 102));
        pg1.setToolTipText("");
        pg1.setValue(100);
        pg1.setStringPainted(true);
        pg1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pg1StateChanged(evt);
            }
        });

        jLabel38.setText("Hada 1");

        jLabel39.setText("Salud 1");

        pg2.setValue(100);
        pg2.setStringPainted(true);
        pg2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pg2StateChanged(evt);
            }
        });

        jLabel40.setText("Salud 2");

        jButton9.setText("COMENZAR BATALLA");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addGap(239, 239, 239))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_player1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pg1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel37)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_player2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pg2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel38))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton9)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(cb_player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pelea", jPanel4);

        jMenu1.setText("File");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar Como");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
        ap.cargarArchivoBinario();
        
        
        String Nombre;
        int edad;
        float altura;
        float salud = 475;
        float poder = 57;
        int branquias;
        int aletas;
        
        Nombre = tf_nombreLamia.getText();
        edad = Integer.parseInt(tf_edadLamia.getText());
        altura= Float.parseFloat(tf_alturaLamias.getText());
        branquias = Integer.parseInt(tf_NBranquiasLamias.getText());
        aletas = Integer.parseInt(tf_AletasLamia.getText());
        
        Hadas x = new Lamias(aletas, branquias, Nombre, altura, poder, salud, edad);
        
        hadas.add(x);
        ap.setHada(x);
        
        JOptionPane.showMessageDialog(this, "Se a agregado exitosamente");
        
            
       
        
        
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Usuario guardado exitosamente");
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
        ap.cargarArchivoBinario();
        
        int alas;
        String Nombre;
        int edad;
        float altura;
        float salud = 563;
        float poder = 67;
        
        alas = Integer.parseInt(tf_NAlasSilfides.getText());
        Nombre = tf_nombreSilfides.getText();
        edad = Integer.parseInt(tf_edadSilfides.getText());
        altura= Float.parseFloat(tf_alturaSilfides.getText());
        
        hadas.add(new Silfides(alas, Nombre, altura, poder, salud, edad));
        
        JOptionPane.showMessageDialog(this, "Se a agregado exitosamente");
        
        Hadas x = new  Silfides(alas, Nombre, altura, poder, salud, edad);
        
        hadas.add(x);
        ap.setHada(x);
        
     
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        ap.cargarArchivoBinario();
  
    
        String Nombre;
        int edad;
        float altura;
        float salud = 373;
        float poder = 78;
        float saludArbol = 173;
        
        
        
        Nombre = tf_nombreHamadrades.getText();
        edad = Integer.parseInt(tf_edadHamadrades.getText());
        altura= Float.parseFloat(tf_alturaHamadrade.getText());
        
        Hadas x = new Hamadriades(saludArbol, Nombre, altura, poder, salud, edad) ;
        
        hadas.add(x);
        ap.setHada(x);
        
     
        JOptionPane.showMessageDialog(this, "Se a agregado exitosamente");
       
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
            
        ap.cargarArchivoBinario();
         
        String Nombre;
        int edad;
        float altura;
        float salud = 683;
        float poder = 71;
        int alas;
        
        Nombre = tf_nombreSalamandra.getText();
        edad = Integer.parseInt(tf_edadSalamandras.getText());
        altura= Float.parseFloat(tf_alturaSalamandras.getText());
        alas = Integer.parseInt(tf_NAlasSalamandras.getText());
        
        hadas.add(new Salamandras(alas, Nombre, altura, poder, salud, edad));
        
        
        Hadas x = new  Salamandras(alas, Nombre, altura, poder, salud, edad);
        
        hadas.add(x);
        ap.setHada(x);
        
       
        JOptionPane.showMessageDialog(this, "Se a agregado exitosamente");
       
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
        String Nombre;
        int edad;
        float altura;
        float salud = 475;
        float poder = 57;
        int branquias;
        int aletas;
        
        Nombre = tf_nombreLamia1.getText();
        edad = Integer.parseInt(tf_edadLamia1.getText());
        altura= Float.parseFloat(tf_alturaLamias1.getText());
        branquias = Integer.parseInt(tf_NBranquiasLamias1.getText());
        aletas = Integer.parseInt(tf_AletasLamia1.getText());
        
        cb_lamias.getItemAt(cb_lamias.getSelectedIndex()).setNombre(Nombre);
        cb_lamias.getItemAt(cb_lamias.getSelectedIndex()).setEstatura(altura);
        cb_lamias.getItemAt(cb_lamias.getSelectedIndex()).setEdad(edad);
        cb_lamias.getItemAt(cb_lamias.getSelectedIndex()).setBranquias(branquias);
        cb_lamias.getItemAt(cb_lamias.getSelectedIndex()).setAleta(aletas);
        
        JOptionPane.showMessageDialog(this, "Se a modificado exitosamente");

        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        
        String Nombre;
        int edad;
        float altura;
        float salud = 373;
        float poder = 78;
        float saludArbol = 173;
        
        
        
        Nombre = tf_nombreHamadrades1.getText();
        edad = Integer.parseInt(tf_edadHamadrades1.getText());
        altura= Float.parseFloat(tf_alturaHamadrade1.getText());
        
        cb_Hamadrades.getItemAt(cb_Hamadrades.getSelectedIndex()).setNombre(Nombre);
        cb_Hamadrades.getItemAt(cb_Hamadrades.getSelectedIndex()).setEstatura(altura);
        cb_Hamadrades.getItemAt(cb_Hamadrades.getSelectedIndex()).setEdad(edad);
        
        JOptionPane.showMessageDialog(this, "Se a modificado exitosamente");
       
       
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
                int alas;
        String Nombre;
        int edad;
        float altura;
        float salud = 563;
        float poder = 67;
        
        alas = Integer.parseInt(tf_NAlasSilfides1.getText());
        Nombre = tf_nombreSilfides1.getText();
        edad = Integer.parseInt(tf_edadSilfides1.getText());
        altura= Float.parseFloat(tf_alturaSilfides1.getText());
        
        
        cb_silfides.getItemAt(cb_silfides.getSelectedIndex()).setNombre(Nombre);
        cb_silfides.getItemAt(cb_silfides.getSelectedIndex()).setEstatura(altura);
        cb_silfides.getItemAt(cb_silfides.getSelectedIndex()).setEdad(edad);
        cb_silfides.getItemAt(cb_silfides.getSelectedIndex()).setAlas(alas);
        
        JOptionPane.showMessageDialog(this, "Se a modificado exitosamente");
       
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
          
        String Nombre;
        int edad;
        float altura;
        float salud = 683;
        float poder = 71;
        int alas;
        
        Nombre = tf_nombreSalamandra1.getText();
        edad = Integer.parseInt(tf_edadSalamandras1.getText());
        altura= Float.parseFloat(tf_alturaSalamandras1.getText());
        alas = Integer.parseInt(tf_NAlasSalamandras1.getText());
       
        cb_Salamandras.getItemAt(cb_Salamandras.getSelectedIndex()).setNombre(Nombre);
        cb_Salamandras.getItemAt(cb_Salamandras.getSelectedIndex()).setEstatura(altura);
        cb_Salamandras.getItemAt(cb_Salamandras.getSelectedIndex()).setEdad(edad);
        cb_Salamandras.getItemAt(cb_Salamandras.getSelectedIndex()).setAlas(alas);
        
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        // Guardar 
        
        if (ap.getArchivo() == null) {
            JFileChooser jfc = new JFileChooser();
            int seleccion = jfc.showSaveDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                ap.setArchivo(jfc.getSelectedFile());
                ap.escribirArchivo();
            }
        } else {
            ap.escribirArchivo();
        }
      
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        int seleccion = jfc.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            ap.setArchivo(jfc.getSelectedFile());
            ap.escribirArchivo();
        }
        ap.escribirArchivo();
        
        
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Hadas t : hadas) {
            if (t instanceof Silfides) {
                model.addElement(t);
            }
        }
        cb_silfides.setModel(model);
        
        model = new DefaultComboBoxModel();
        for (Hadas t : hadas) {
            if (t instanceof Salamandras) {
                model.addElement(t);
            }
        }
        cb_Salamandras.setModel(model);
        model = new DefaultComboBoxModel();
        for (Hadas t : hadas) {
            if (t instanceof Hamadriades) {
                model.addElement(t);
            }
        }
        cb_Hamadrades.setModel(model);
        model = new DefaultComboBoxModel();
        for (Hadas t : hadas) {
            if (t instanceof Lamias) {
                model.addElement(t);
            }
        }
        cb_lamias.setModel(model);
        
        model = new DefaultComboBoxModel();
        for (Hadas t : hadas) {
               model.addElement(t);
           
        }
        cb_player1.setModel(model);
        
        model = new DefaultComboBoxModel();
        for (Hadas t : hadas) {
               model.addElement(t);
           
        }
        cb_player2.setModel(model);
        
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    
    String carpeta_guardada;
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            JFileChooser jfc = new JFileChooser();
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION){
                
                ap.setArchivo(jfc.getSelectedFile());
                ap.cargarArchivoBinario();
                ap.escribirArchivo();
            
            }
   
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void pg2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pg2StateChanged
       /*
        pg2.setValue((int) cb_player2.getItemAt(cb_player2.getSelectedIndex()).getSalud());
        */
    }//GEN-LAST:event_pg2StateChanged

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered
        /*
        pg2.setValue((int) cb_player2.getItemAt(cb_player2.getSelectedIndex()).getSalud());
        pg1.setValue((int) cb_player1.getItemAt(cb_player1.getSelectedIndex()).getSalud());
        
        */
    }//GEN-LAST:event_jTabbedPane1MouseEntered

    private void pg1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pg1StateChanged
        /*
        pg1.setValue((int) cb_player1.getItemAt(cb_player1.getSelectedIndex()).getSalud());
        */
    }//GEN-LAST:event_pg1StateChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                
        if (ap1.getPlayer1() instanceof Hamadriades && ap2.getPlayer2()instanceof Salamandras){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1() instanceof Hamadriades && ap2.getPlayer2()instanceof Hamadriades){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        
              if (ap1.getPlayer1()instanceof Salamandras && ap2.getPlayer2()instanceof Silfides){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1()instanceof Salamandras && ap2.getPlayer2()instanceof Hamadriades){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1()instanceof Salamandras && ap2.getPlayer2()instanceof Salamandras){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1()instanceof Hamadriades && ap2.getPlayer2() instanceof Lamias){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1()instanceof Hamadriades && ap2.getPlayer2()instanceof Silfides){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap1.start();
            ap2.start();
        }
  
        
        if (ap1.getPlayer1() instanceof Lamias && ap2.getPlayer2() instanceof Silfides){
            ap1 = new ThreadBatallas(pg1, pg2, 
                    cb_player1.getItemAt(cb_player1.getSelectedIndex()),
                    cb_player2.getItemAt(cb_player2.getSelectedIndex()));
            ap2 = new ThreadBatallas(pg1, pg2, 
                    cb_player1.getItemAt(cb_player1.getSelectedIndex()),
                    cb_player2.getItemAt(cb_player2.getSelectedIndex()));
            
            ap1.start();
            ap2.start();
        }
        
        if (ap1.getPlayer1() instanceof Lamias && ap2.getPlayer2() instanceof Salamandras){
            ap1 = new ThreadBatallas(pg1, pg2, 
                    (Hadas)cb_player1.getSelectedItem(),
                    (Hadas)cb_player2.getSelectedItem());
            ap1.start();
            ap2.start();
        }
          if (ap1.getPlayer1()instanceof Salamandras && ap2.getPlayer2()instanceof Lamias){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        
        if (ap1.getPlayer1()instanceof Lamias && ap2.getPlayer2()instanceof Hamadriades){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1() instanceof Lamias && ap2.getPlayer2() instanceof Lamias){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1()instanceof Silfides && ap2.getPlayer2() instanceof Lamias){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1() instanceof Silfides && ap2.getPlayer2()instanceof Salamandras){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1()instanceof Silfides && ap2.getPlayer2() instanceof Hamadriades){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
        if (ap1.getPlayer1()instanceof Silfides && ap2.getPlayer2()instanceof Silfides){
            ap1 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            ap2 = new ThreadBatallas(pg1, pg2, (Hadas)cb_player1.getSelectedItem(), (Hadas)cb_player2.getSelectedItem());
            
            ap1.start();
            ap2.start();
        }
      
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JOptionPane.showMessageDialog(this, "Trata sobre un juego de combate entre hadas, y de como fiallos deja su facebook abierto");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalLab8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Hamadriades> cb_Hamadrades;
    private javax.swing.JComboBox<Salamandras> cb_Salamandras;
    private javax.swing.JComboBox<Lamias> cb_lamias;
    private javax.swing.JComboBox<Hadas> cb_player1;
    private javax.swing.JComboBox<Hadas> cb_player2;
    private javax.swing.JComboBox<Silfides> cb_silfides;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JProgressBar pg1;
    private javax.swing.JProgressBar pg2;
    private javax.swing.JTextField tf_AletasLamia;
    private javax.swing.JTextField tf_AletasLamia1;
    private javax.swing.JTextField tf_NAlasSalamandras;
    private javax.swing.JTextField tf_NAlasSalamandras1;
    private javax.swing.JTextField tf_NAlasSilfides;
    private javax.swing.JTextField tf_NAlasSilfides1;
    private javax.swing.JTextField tf_NBranquiasLamias;
    private javax.swing.JTextField tf_NBranquiasLamias1;
    private javax.swing.JTextField tf_alturaHamadrade;
    private javax.swing.JTextField tf_alturaHamadrade1;
    private javax.swing.JTextField tf_alturaLamias;
    private javax.swing.JTextField tf_alturaLamias1;
    private javax.swing.JTextField tf_alturaSalamandras;
    private javax.swing.JTextField tf_alturaSalamandras1;
    private javax.swing.JTextField tf_alturaSilfides;
    private javax.swing.JTextField tf_alturaSilfides1;
    private javax.swing.JTextField tf_edadHamadrades;
    private javax.swing.JTextField tf_edadHamadrades1;
    private javax.swing.JTextField tf_edadLamia;
    private javax.swing.JTextField tf_edadLamia1;
    private javax.swing.JTextField tf_edadSalamandras;
    private javax.swing.JTextField tf_edadSalamandras1;
    private javax.swing.JTextField tf_edadSilfides;
    private javax.swing.JTextField tf_edadSilfides1;
    private javax.swing.JTextField tf_nombreHamadrades;
    private javax.swing.JTextField tf_nombreHamadrades1;
    private javax.swing.JTextField tf_nombreLamia;
    private javax.swing.JTextField tf_nombreLamia1;
    private javax.swing.JTextField tf_nombreSalamandra;
    private javax.swing.JTextField tf_nombreSalamandra1;
    private javax.swing.JTextField tf_nombreSilfides;
    private javax.swing.JTextField tf_nombreSilfides1;
    // End of variables declaration//GEN-END:variables

    ArrayList<Hadas> hadas = new ArrayList();
    static AdminHadas ap = new AdminHadas("./Hadas.cbm");
    ThreadBatallas ap1;
    ThreadBatallas ap2;
}
